<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="eip" nsURI="http://www.github.com/lbroudoux/dsl/eip/1.0" nsPrefix="eip">
  <eClassifiers xsi:type="ecore:EClass" name="Endpoint" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="toChannel" eType="#//Channel"
        eOpposite="#//Channel/fromEndpoint"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fromChannel" eType="#//Channel"
        eOpposite="#//Channel/toEndpoint"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Channel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="toEndpoint" eType="#//Endpoint"
        eOpposite="#//Endpoint/fromChannel"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fromEndpoint" eType="#//Endpoint"
        eOpposite="#//Endpoint/toChannel"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Adapter"/>
  <eClassifiers xsi:type="ecore:EClass" name="Router" eSuperTypes="#//Endpoint">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedRoutes" upperBound="-1"
        eType="#//ConditionalRoute" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Filter" eSuperTypes="#//Endpoint">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="expression" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Transformer" eSuperTypes="#//Endpoint"/>
  <eClassifiers xsi:type="ecore:EClass" name="Gateway" eSuperTypes="#//Endpoint"/>
  <eClassifiers xsi:type="ecore:EClass" name="ConditionalRoute">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="condition" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="channel" lowerBound="1"
        eType="#//Channel"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Splitter" eSuperTypes="#//Endpoint"/>
  <eClassifiers xsi:type="ecore:EClass" name="Aggregator" eSuperTypes="#//Endpoint"/>
  <eClassifiers xsi:type="ecore:EClass" name="Route">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedEndpoints" upperBound="-1"
        eType="#//Endpoint" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedChannels" upperBound="-1"
        eType="#//Channel" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ServiceActivator" eSuperTypes="#//Endpoint"/>
  <eClassifiers xsi:type="ecore:EClass" name="EIPModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedRoutes" upperBound="-1"
        eType="#//Route" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Enricher" eSuperTypes="#//Endpoint">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="part" eType="#//MessagePart"
        defaultValueLiteral="PAYLOAD"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="MessagePart">
    <eLiterals name="HEADER"/>
    <eLiterals name="PAYLOAD"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CompositeProcessor" eSuperTypes="#//Endpoint">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedEndpoints" upperBound="-1"
        eType="#//Endpoint" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
